# Generated by Django 4.2.7 on 2024-01-14 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 1, 0)),
        ),
    ]
