# Generated by Django 4.2.8 on 2023-12-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
    ]
