# Generated by Django 4.2.7 on 2023-12-31 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pragraph',
            name='Text',
            field=models.TextField(default='this is a text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pragraph',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pragraph', to='notes.note'),
        ),
    ]
