# Generated by Django 4.2.7 on 2023-12-31 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_pragraph_text_alter_pragraph_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='notes.note'),
        ),
    ]
