# Generated by Django 4.2.7 on 2023-12-31 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_link_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pragraph',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.CharField(default='http://example.com', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pragraph',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
