# Generated by Django 4.2.7 on 2023-12-31 13:39

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_pragraph_options_link_url_pragraph_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pragraph',
            name='Text',
        ),
        migrations.AddField(
            model_name='pragraph',
            name='content',
            field=django_quill.fields.QuillField(default='this is empty'),
            preserve_default=False,
        ),
    ]
